test:
	grunt test

watch-test:
	grunt

init-test:
	git submodule add https://github.com/pivotal/jasmine.git spec/vendor/jasmine
	git submodule init
	npm install

update-test:
	git submodule update
	npm install
