test:
	grunt test

watch-test:
	grunt watch

init-test:
	git submodule add https://github.com/jquery/qunit.git spec/vendor/qunit
	git submodule init
	npm install

update-test:
	git submodule update
	npm install
